

[colors]
light_pink='#f77'


[c3.r0]
text="c3.r0"
button_schema_classes=""
key="g"
color='light_pink'

[r3.c0]
text="r3.c0"
button_schema_classes=""
key="g"
color='light_pink'

[r5.c2]
text="alt+w"
key="alt+w"
toggle=false
color='blue'
# img='assets/minecraft.jpg'

[c1.r0]
text="alt+w"
key="alt+w"
toggle=false
color='blue'
# img='assets/minecraft.jpg'

[c0.r1]
text="asdfasdfasdf"
key="asdfasdfasdf"
toggle=false
color='blue'
# img='assets/minecraft.jpg'

[c2.r2]
text="r2c2"
key="r2c2"
toggle=false
color='blue'

[c3.r2]
text="c,t,r,l,+,1"
key="asdf"
toggle=false
color='blue'

[c7.r3]
text="7,3"
key="ctrl+c,asdf,,"
toggle=false
color='green'
